### PR TITLE
Adding efficiency, visualization, and convergency tests to dipole.ipynb.

### PR DESCRIPTION
**Pull request by Luochenghuang**
This is an attempt to complete the dipole.ipynb notebook.
Please let me know there are mistakes.
Thank you!

### CODE REVIEW

**Comment by Luochenghuang** [comment]
Apparently there is a bug where if you include output images in the .ipynb then the docs build fails because the pipeline doesn't save the images. It's should be fixed now.

**Review by smartalecH — APPROVED** [review]
This looks great, thanks for doing this! I especially love the sweep with # of Fourier terms. Very clear.

Looking forward to what comes next!

**Comment by smartalecH** [comment]
(Also, thanks for fixing that bug with the image output)

**Comment by Luochenghuang** [comment]
Thank you for reviewing!

**Pull request merged**
